


services:
  pipeline-con-apirest:
    build: .
    volumes:
      - ./output:/app/output
    environment:
      API_KEY: ${API_KEY}
      API_EMAIL: ${API_EMAIL}
      API_BASE_URL: ${API_BASE_URL}